apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" .Release.Name "clusterrole" }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  #base ressources
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources:
      - configmaps
      - endpoints
      - horizontalpodautoscalers
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - secrets
      - serviceaccounts
      - services
  - apiGroups: ["apps"]
    verbs: ["get", "list"]
    resources:
      - deployments
      - statefulsets
      - replicasets
      - daemonsets
  - apiGroups: ["networking.k8s.io"]
    verbs: ["get", "list"]
    resources:
      - networkpolicies
      - ingresses
  - apiGroups: ["autoscaling"]
    verbs: ["get", "list"]
    resources:
      - horizontalpodautoscalers  
  - apiGroups: ["rbac.authorization.k8s.io"]
    verbs: ["get", "list"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
  - apiGroups: ["metrics.k8s.io"]
    verbs: ["get", "list"]
    resources:
      - pods
      - nodes
  - apiGroups: ["policy"]
    verbs: ["get", "list"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies