apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" .Release.Name "sa" }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  