apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name "config-popeye" }}
  namespace: {{ .Release.Namespace }}
data:
  spinach.yml: |
    {{- .Values.popeyeConfigugration | toYaml | nindent 4 }}
