apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" .Release.Name "cronjob" }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  failedJobsHistoryLimit: {{ .Values.cronJob.history.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.history.successfulJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      namespace: {{ .Release.Namespace }}
    spec:
      template:
        spec:
          serviceAccountName: {{ printf "%s-%s" .Release.Name "sa" }}
          securityContext:
            {{- toYaml .Values.cronJob.securityContext | nindent 12 }}
          restartPolicy: Never
          imagePullSecrets:
            {{- toYaml .Values.cronJob.imagePullSecrets | nindent 12 }}
          containers:
            - name: {{ printf "%s-%s" .Release.Name "container" }}
              image: "{{ .Values.cronJob.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.cronJob.image.pullPolicy }}
              args:
                {{- if .Values.popeyeConfigugration }}
                - "-f /tmp/spinach.yml"
                {{- end }}
                - --force-exit-zero=true
                - --out={{ .Values.cronJob.containerConfiguration.outputFormat }}
                {{- if and (eq .Values.cronJob.containerConfiguration.outputFormat "prometheus") (.Values.cronJob.containerConfiguration.prometheus.address) }}
                - --pushgateway-address={{ .Values.cronJob.containerConfiguration.prometheus.address }}
                {{- if .Values.cronJob.containerConfiguration.prometheus.basicAuth.enabled }}
                - --pushgateway-basic-auth-user={{ .Values.cronJob.containerConfiguration.prometheus.basicAuth.user }}
                - --pushgateway-basic-auth-pass=$PROM_BASIC_AUTH_PW
                {{- end }}
                {{- end }}
              {{- if and (eq .Values.cronJob.containerConfiguration.outputFormat "prometheus") (.Values.cronJob.containerConfiguration.prometheus.basicAuth.enabled) }}
              env:
                - name: PROM_BASIC_AUTH_PW
                  valueFrom:
                    secretKeyRef:
                      name: {{ printf "%s-%s" .Release.Name "secret" }}
                      key: prom-password
              {{- end }}
              resources:
                {{- toYaml .Values.cronJob.resources | nindent 16 }}
              {{- if .Values.popeyeConfigugration }}
              volumeMounts:
                - name: configuration
                  mountPath: /tmp
              {{- end }}
          nodeSelector:
            {{- toYaml .Values.cronJob.nodeSelector | nindent 12 }}
          affinity:
            {{- toYaml .Values.cronJob.affinity | nindent 12 }}
          tolerations:
            {{- toYaml .Values.cronJob.tolerations | nindent 12 }}
          {{- if .Values.popeyeConfigugration }}
          volumes:
            - name: configuration
              configMap:
                name: {{ printf "%s-%s" .Release.Name "config-popeye" }}
          {{- end }}
