apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" .Release.Name "cronjob" }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  failedJobsHistoryLimit: {{ .Values.cronJob.history.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.history.successfulJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      namespace: {{ .Release.Namespace }}
    spec:
      template:
        spec:
          serviceAccountName: {{ printf "%s-%s" .Release.Name "sa" }}
          {{- if not (.Values.cronJob.securityContext | empty) }}
          securityContext:
            {{- toYaml .Values.cronJob.securityContext | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          {{- if not (.Values.cronJob.imagePullSecrets | empty) }}
          imagePullSecrets:
            {{- toYaml .Values.cronJob.imagePullSecrets | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ printf "%s-%s" .Release.Name "container" }}
              image: "{{ .Values.cronJob.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.cronJob.image.pullPolicy }}
              {{- if not (.Values.job.securityContext | empty) }}
              securityContext:
                {{- toYaml .Values.job.securityContext | nindent 16 }}
              {{- end }}
              args:
                {{- if .Values.popeyeConfiguration }}
                - "-f /tmp/popeyeconfiguration/spinach.yml"
                {{- end }}
                - --force-exit-zero=true
                - --out={{ .Values.cronJob.containerConfiguration.outputFormat }}
                {{- if and (eq .Values.cronJob.containerConfiguration.outputFormat "prometheus") (.Values.cronJob.containerConfiguration.prometheus.address) }}
                - --push-gtwy-url={{ .Values.cronJob.containerConfiguration.prometheus.address }}
                {{- if .Values.cronJob.containerConfiguration.prometheus.basicAuth.enabled }}
                - --push-gtwy-user={{ .Values.cronJob.containerConfiguration.prometheus.basicAuth.user }}
                - --push-gtwy-password=$PROM_BASIC_AUTH_PW
                {{- end }}
                {{- end }}
              {{- if and (eq .Values.cronJob.containerConfiguration.outputFormat "prometheus") (.Values.cronJob.containerConfiguration.prometheus.basicAuth.enabled) }}
              env:
                - name: PROM_BASIC_AUTH_PW
                  valueFrom:
                    secretKeyRef:
                      name: {{ printf "%s-%s" .Release.Name "secret" }}
                      key: prom-password
              {{- end }}
              {{- if not (.Values.job.resources | empty) }}
              resources:
                {{- toYaml .Values.job.resources | nindent 16 }}
              {{- end }}
              {{- if .Values.popeyeConfiguration }}
              volumeMounts:
                - name: configuration
                  mountPath: /tmp/popeyeconfiguration
              {{- end }}
          {{- if not (.Values.cronJob.nodeSelector | empty) }}
          nodeSelector:
            {{- toYaml .Values.cronJob.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if not (.Values.cronJob.affinity | empty) }}
          affinity:
            {{- toYaml .Values.cronJob.affinity | nindent 12 }}
          {{- end }}
          {{- if not (.Values.cronJob.tolerations | empty) }}
          tolerations:
            {{- toYaml .Values.cronJob.tolerations | nindent 12 }}
          {{- end }}
          {{- if .Values.popeyeConfiguration }}
          volumes:
            - name: configuration
              configMap:
                name: {{ printf "%s-%s" .Release.Name "config-popeye" }}
          {{- end }}
