---
{{- if .Values.cronJob.containerConfiguration.prometheus.basicAuth.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "secret" }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  prom-password: {{ .Values.cronJob.containerConfiguration.prometheus.basicAuth.password | b64enc }}
{{- end }}
