{{- if and (.Values.cronJob.prometheus.basicAuth.enabled) (not .Values.cronJob.prometheus.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "secret" }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  prom-password: {{ .Values.cronJob.prometheus.basicAuth.password | b64enc }}
{{- end }}
