name: helm-package-and-deploy

on:
  push:
    branches:
      - dev

jobs:
  package-and-deploy-dev:
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/deb4sh/ci-helm-image:sha-1171f2a
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags      
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print tolower($2)}') >> $GITHUB_OUTPUT
          echo REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT
          echo REPO_VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_OUTPUT
          echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Append Git Sha to version
        id: append_version
        env:
          SHORT_SHA: ${{ steps.meta.outputs.SHA_SHORT }}  
        run: |
          sed -E -i '0,/version:/s/version: ([0-9]+\.?){3}/\0-'$SHORT_SHA'/' Chart.yaml 
          echo HELM_FINAL_VERSION=$(grep -m 1 -Eo '[0-9]{1,}.[0-9]{1,}.[0-9]{1,}' Chart.yaml) >> $GITHUB_OUTPUT
      - name: Package and Sign
        id: package_and_sign
        run: |
          mkdir dist
          helm package --dependency-update ./ --destination dist
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to registry
        if: github.event_name != 'pull_request'
        id: push
        run: |
          helm push ./sample-app-chart-${{ steps.append_version.outputs.VERSION }}.tgz oci://${{ steps.meta.outputs.REPOSITORY }}/${{ steps.meta.outputs.REPO_NAME }}          